import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@components/Navbar";
import { Footer } from "@components/Footer";
import { ThemeProvider } from "@components/ThemeProvider";

export const metadata: Metadata = {
  title: "Izzahnin's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* Prevent flash of wrong theme before React hydrates */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var c=document.cookie.match(/(?:^|;\\s*)theme=([^;]*)/);var t=c?c[1]:(window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');if(t==='dark')document.documentElement.classList.add('dark');})();`,
          }}
        />
      </head>
      <body className="flex-1 bg-[var(--bg)]">
        <ThemeProvider>
          <main className="m-auto">
            <Navbar />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
