import type { Metadata } from "next";
import { cookies } from "next/headers";
import "../globals.css";
import { Navbar } from "@components/Navbar";
import { Footer } from "@components/Footer";
import { ThemeProvider } from "@components/ThemeProvider";

export const metadata: Metadata = {
  title: "Izzahnin's Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const saved = (await cookies()).get("theme")?.value;
  const initialTheme = saved === "dark" || saved === "light" ? saved : undefined;
  const htmlClass = `scroll-smooth${initialTheme === "dark" ? " dark" : ""}`;

  return (
    <html lang="en" className={htmlClass}>
      <head>
        {/* Prevent flash of wrong theme before React hydrates */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var c=document.cookie.match(/(?:^|;\\s*)theme=([^;]*)/);var t=c?c[1]:(window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');if(t==='dark')document.documentElement.classList.add('dark');})();`,
          }}
        />
      </head>
      <body className="flex-1 bg-[var(--bg)]">
        <ThemeProvider defaultTheme={initialTheme}>
          <main className="m-auto">
            <Navbar />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
